# Generated by Django 6.1.1 on 2026-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("skills", models.JSONField(default=list)),
                ("current_load", models.IntegerField(default=0)),
                ("capacity", models.IntegerField(default=5)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
