# Generated by Django 6.1.1 on 2026-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_tickets", "0002_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="frustration_level",
            field=models.CharField(default="low", max_length=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="frustration_score",
            field=models.IntegerField(default=0),
        ),
    ]
