# Generated by Django 6.1.1 on 2026-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_tickets", "0003_ticket_frustration_level_ticket_frustration_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="duplicate_similarity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="duplicate_ticket_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
    ]
